// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4FZnKhOzVO24b4bieRHRuk_0I9wywN2Q',
    appId: '1:642155354036:web:f12a65ef3d6150d8b744e1',
    messagingSenderId: '642155354036',
    projectId: 'medilane-8bdc2',
    authDomain: 'medilane-8bdc2.firebaseapp.com',
    storageBucket: 'medilane-8bdc2.firebasestorage.app',
    measurementId: 'G-3LMQY0QCCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC00yOiYvHEwyQWtjzAJtlwDDTR_ARs0HY',
    appId: '1:642155354036:android:b692fbe557e00c52b744e1',
    messagingSenderId: '642155354036',
    projectId: 'medilane-8bdc2',
    storageBucket: 'medilane-8bdc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqSax0ZS4T3Gp5829jRaVeHBEnqT7HH60',
    appId: '1:642155354036:ios:6c563d7068fed87eb744e1',
    messagingSenderId: '642155354036',
    projectId: 'medilane-8bdc2',
    storageBucket: 'medilane-8bdc2.firebasestorage.app',
    iosBundleId: 'com.example.medilane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqSax0ZS4T3Gp5829jRaVeHBEnqT7HH60',
    appId: '1:642155354036:ios:6c563d7068fed87eb744e1',
    messagingSenderId: '642155354036',
    projectId: 'medilane-8bdc2',
    storageBucket: 'medilane-8bdc2.firebasestorage.app',
    iosBundleId: 'com.example.medilane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4FZnKhOzVO24b4bieRHRuk_0I9wywN2Q',
    appId: '1:642155354036:web:640be155bd1a77c5b744e1',
    messagingSenderId: '642155354036',
    projectId: 'medilane-8bdc2',
    authDomain: 'medilane-8bdc2.firebaseapp.com',
    storageBucket: 'medilane-8bdc2.firebasestorage.app',
    measurementId: 'G-CWBVZ1NVXP',
  );
}
